flaskBlog/main/routes.py
from flask import render_template, Blueprint

main = Blueprint('main', __name__)


@main.route("/")
def main():
	return render_template('index.html')


@main.route("/home")
def home_main():	
	return render_template('home.html')

flaskBlog/users/routes.py
from flask import render_template, url_for, flash, redirect, request, abort, Blueprint
from flaskBlog import db, bcrypt	
from flaskBlog.models import User
from flask_login import login_user, current_user, logout_user, login_required
from flask_mail import Message
from flaskBlog.users.utils import save_profile_picture, send_reset_email
from flaskBlog.users.forms import (RegistrationForm, LoginForm, UpdateAccountForm,
								  RequestResetForm, ResetPasswordForm)
users = Blueprint('users', __name__)

@users.route("/register", methods=['GET', 'POST'])
def register():
	if current_user.is_authenticated:
		return redirect(url_for('main.home'))
	form = RegistrationForm()
	if form.validate_on_submit():
		hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
		user = User(username = form.username.data, email = form.email.data, password = hashed_password)
		db.session.add(user)
		db.session.commit()
		flash('Your Account has been created ! You should be able to Login', 'success')
		return redirect(url_for('users.login'))
	return render_template('register.html', title='Register', form=form)



@users.route("/login", methods=['GET', 'POST'])
def login():
	if current_user.is_authenticated:
		return redirect(url_for('main.home'))
	form = LoginForm()
	if form.validate_on_submit():
		user = User.query.filter_by(email=form.email.data).first()
		if user and bcrypt.check_password_hash(user.password, form.password.data):
			login_user(user, remember=form.remember.data)
			next_page = request.args.get('next')
			return redirect(next_page) if next_page else redirect(url_for('main.home'))
		else:
			flash('Login Unsuccessful, Check email and password', 'danger')

	return render_template('login.html', title='Login', form=form)


@users.route("/logout")
def logout():
	logout_user()
	return render_template('index.html')


@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
	form = UpdateAccountForm()
	if form.validate_on_submit():
		if form.picture.data:
			picture_file = save_profile_picture(form.picture.data)
			current_user.image_file = picture_file
		current_user.username = form.username.data
		current_user.email = form.email.data
		db.session.commit()	
		flash('Your Account has been Updated !', 'success')
		return redirect(url_for('users.account'))		
	elif request.method == 'GET':
		form.username.data = current_user.username
		form.email.data = current_user.email	
	image_file = url_for('static', filename = 'profile_pics/' + current_user.image_file)
	return render_template('account.html', title="Account", image_file=image_file, form=form)




@users.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
	if current_user.is_authenticated:
		return redirect(url_for('main.home'))
	form = RequestResetForm()
	if form.validate_on_submit():
		user = User.query.filter_by(email=form.email.data).first()
		send_reset_email(user)
		flash('An email has been sent with instructions to reset your password.', 'info')
		return redirect(url_for('users.login'))
	return render_template('reset_request.html', title="Reset Password", form=form)


@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_password_with_token(token):
	if current_user.is_authenticated:
		return redirect(url_for('main.home'))
	user = User.verify_reset_token(token)
	if user is None:
		flash('That is an invalid or expired token', 'warning')
		return redirect(url_for('users.reset_request'))
	form = ResetPasswordForm()
	if form.validate_on_submit():
		print("ResetPasswordForm has been validated")
		hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
		user.password = hashed_password
		db.session.commit()
		flash('Your Account has been updated ! You should be able to Login', 'success')
		return redirect(url_for('users.login'))
	print("ResetPasswordForm has NOT been validated")
	return render_template('reset_token.html', title="Reset Password", form=form) 

flaskBlog/templates/about.html
{% extends "layout.html" %}




{% block content %}


{% endblock content %}

flaskBlog/templates/account.html
{% extends "layout.html" %}




{% block content %}

<div class="content-section">
  <div class="media">
    <img class="rounded-circle account-img" src="{{ image_file }}">
    <div class="media-body">
      <h2 class="account-heading">{{ current_user.username }}</h2>
      <p class="text-secondary">{{ current_user.email }}</p>
    </div>
  </div>
		<form method="POST" action="" enctype="multipart/form-data">
			{{ form.hidden_tag() }}
			<fieldset class="form-group">
				<legend class="border-bottom mb-4"> Account Info </legend>
				<div class="form-group">
					{{ form.username.label(class="form-control-label") }}

					{% if form.username.errors %}
						{{ form.username(class="form-control form-control-lg is-invalid") }}
						<div class="invalid-feedback">
							{% for error in form.username.errors %}
								<span>{{ error }}</span>
							{% endfor %}
						</div>	
					{% else %}
							{{ form.username(class="form-control form-control-lg") }}
				
					{% endif %}
				</div>
				<div class="form-group">
					{{ form.email.label(class="form-control-label") }}
					
					{% if form.email.errors %}
						{{ form.email(class="form-control form-control-lg is-invalid") }}
						<div class="invalid-feedback">
							{% for error in form.email.errors %}
								<span>{{ error }}</span>
							{% endfor %}
						</div>

					{% else %}
							{{ form.email(class="form-control form-control-lg") }}
				
					{% endif %}
				</div>
				<div class="form-group">
					{{ form.picture.label() }}
					{{ form.picture(class="form-control-file") }}

					{% if form.picture.errors %}
						{% for error in form.picture.errors %}
								<span class="text-danger">{{ error }}</span>
							{% endfor %}	
					{% endif %}

				</div>
			</fieldset>
			<div class="form-group">
				{{ form.submit(class="btn btn-outline-info") }}
			</div>
		</form>
</div>
{% endblock content %}

flaskBlog/templates/home.html
{% extends "layout.html" %}

{% block content %}

  
  <h1>
      This is the Home Page.
  </h1>

{% endblock content %}

flaskBlog/templates/index.html
{% extends "layout.html" %}




{% block content %}
<h1>Index Page of all the links</h1>

{% endblock content %}

flaskBlog/templates/layout.html
<!DOCTYPE html>
<html>

<head>
    <!-- Required meta tags -->
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>{{ title }}</title>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
	<script src="https://use.fontawesome.com/releases/v5.0.8/js/all.js"></script>
    <link rel="stylesheet" type="text/css" href=" {{ url_for('static', filename='main.css')}} " >

</head>
<body>

	 <header class="site-header">

 <nav class="navbar navbar-expand-md fixed-top" style="background-color: #5a6065;">	
 	<div class="container-fluid">
		<a class="navbar-brand" href="/"><img src="{{ url_for('static',
       filename='nav/logo.png')}}"></a>

		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive">
			<span class="navbar-toggler-icon"></span>
		</button>
		<div class="collapse navbar-collapse" id="navbarResponsive">
			<ul class="navbar-nav ml-auto">
				<li class="nav-item-active">
					<a class="nav-link" href="{{ url_for('main.home') }}">Home</a>
				</li>				
				{% if current_user.is_authenticated %}
				<li class="nav-item-active">
					<a class="nav-link" href="{{ url_for('users.logout') }}">Logout</a>
				</li>
				<li class="nav-item-active">
					<a class="nav-link" href="{{ url_for('users.account') }}">Account</a>
				</li>

            	{% else %}
				<li class="nav-item-active">
					<a class="nav-link" href="{{ url_for('users.login') }}">Login</a>
				</li>
				<li class="nav-item-active">
					<a class="nav-link" href="{{ url_for('users.register') }}">Register</a>
				</li>
				{% endif %}
				
			</ul>
		</div>
	</div>
</nav>	      
	</header>


	   <main role="main" class="container">
	      <div class="row">
	        <div class="col-md-8">
	        	{% with messages = get_flashed_messages(with_categories=true) %}
	        		{% if messages %}
	        			{% for category, message in messages %}
	        			<div class="alert alert-{{ category }}">
	        				{{ message }}
	        			</div>
	        			{% endfor %}	
	        		{% endif %}
	        	{% endwith %}
	          {% block content %}{% endblock %}
	        </div>
		</main>

	<!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

flaskBlog/templates/layout_bkp.html
<!DOCTYPE html>
<html>

<head>
    <!-- Required meta tags -->
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>{{ title }}</title>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
	<script src="https://use.fontawesome.com/releases/v5.0.8/js/all.js"></script>
    <link rel="stylesheet" type="text/css" href=" {{ url_for('static', filename='main.css')}} " >

</head>
<body>

	 <header class="site-header">



<nav class="navbar navbar-expand-md navbar-light bg-light sticky-top">
	<div class="container-fluid">
		<a class="navbar-brand" href="/"><img src="{{ url_for('static',
       filename='nav/logo.png')}}"></a>

		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive">
			<span class="navbar-toggler-icon"></span>
		</button>
		<div class="collapse navbar-collapse" id="navbarResponsive">
			<ul class="navbar-nav ml-auto">
				<li class="nav-item-active">
					<a class="nav-link" href="{{ url_for('home') }}">Home</a>
				</li>
				<li class="nav-item-active">
					<a class="nav-link" href="{{ url_for('about') }}">About</a>
				</li>
				
				{% if current_user.is_authenticated %}

				<li class="nav-item-active">
					<a class="nav-link" href="{{ url_for('new_post') }}">New post</a>
				</li>
				<li class="nav-item-active">
					<a class="nav-link" href="{{ url_for('logout') }}">Logout</a>
				</li>
				<li class="nav-item-active">
					<a class="nav-link" href="{{ url_for('account') }}">Account</a>
				</li>

            	{% else %}
				<li class="nav-item-active">
					<a class="nav-link" href="{{ url_for('login') }}">Login</a>
				</li>
				<li class="nav-item-active">
					<a class="nav-link" href="{{ url_for('register') }}">Register</a>
				</li>
				{% endif %}
				
			</ul>
		</div>
	</div>
</nav>	      
	</header>


	   <main role="main" class="container">
	      <div class="row">
	        <div class="col-md-8">
	        	{% with messages = get_flashed_messages(with_categories=true) %}
	        		{% if messages %}
	        			{% for category, message in messages %}
	        			<div class="alert alert-{{ category }}">
	        				{{ message }}
	        			</div>
	        			{% endfor %}	
	        		{% endif %}
	        	{% endwith %}
	          {% block content %}{% endblock %}
	        </div>
		</main>

	<!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

flaskBlog/templates/login.html
{% extends "layout.html" %}


{% block content %}

	<div class="form-section">
		<form method="POST" action="">
			{{ form.hidden_tag() }}
			<fieldset class="form-group">
				<legend class="border-bottom mb-4"> Log In </legend>
				
				<div class="form-group">
					{{ form.email.label(class="form-control-label") }}
					{% if form.email.errors %}
						{{ form.email(class="form-control form-control-lg is-invalid") }}
						<div class="invalid-feedback">
							{% for errors in form.email.errors%}
								<span>{{ error }}</span>
							{%  endfor %}
						</div>

					{% else %}
							{{ form.email(class="form-control form-control-lg") }}
				
					{% endif %}
				</div>
				<div class="form-group">
					{{ form.password.label(class="form-control-label") }}
					{% if form.password.errors %}
						{{ form.password(class="form-control form-control-lg is-invalid") }}
						<div class="invalid-feedback">
							{% for errors in form.password.errors%}
								<span>{{ error }}</span>
							{%  endfor %}
						</div>

					{% else %}
							{{ form.password(class="form-control form-control-lg") }}
				
					{% endif %}
				</div>

				<div class="form-check">
					{{ form.remember(class="form-check-input") }}
					{{ form.remember.label(class="form-check-label") }}
				</div>
			</fieldset>
			<div class="form-group">
				{{ form.submit(class="btn btn-outline-info") }}
				<small class="text-muted">
					<a href="{{ url_for('users.reset_request') }}">Forgot Password ?</a>
				</small>
			</div>
			

	<div class="form-group">
		<small class="text-muted">
			Need an Account !!!
			<a class="ml-2" href="{{ url_for('users.register') }}"> Register </a>
		</small>
	</div>

		</form>
	</div>


{% endblock content %}

flaskBlog/templates/main.html
{% extends "layout.html" %}


{% block content %}



<embed src="http://localhost:5000/static/Manifesto.pdf" width="500" height="375">


<form method="POST" enctype="multipart/form-data" action="/upload">
  <input type="file" name="file[]" multiple="">
  <input type="submit" value="add">
</form>


<div class="panel-footer">
  <label for="input-2" class="control-label">My Rating:</label>
<input id="stars_123}}" name="input-2" class="rating rating-loading" data-min="0" data-max="10" data-step="0.1" data-stars="10" data-size="xs"onchange="updateStars('123')" >
</div>
<script type="text/javascript">
    function updateStars(id) {

       var rating = document.getElementById("stars_" + id).value;
      console.log("rating is : " + rating);
       $.ajax({
           url : '/rate_movie',
           headers: {"Content-Type": "application/json"},
           type : 'POST',
           dataType: 'json',
           data : JSON.stringify{'id': 'id', 'rating': rating}
           });
};
</script>

{% endblock content %}

flaskBlog/templates/main_carousel.html
{% extends "layout.html" %}


{% block content %}



<div id="demo" class="carousel slide" data-ride="carousel">

  <!-- Indicators -->
  <ul class="carousel-indicators">
    <li data-target="#demo" data-slide-to="0" class="active"></li>
    <li data-target="#demo" data-slide-to="1"></li>
    <li data-target="#demo" data-slide-to="2"></li>
  </ul>
  
  <!-- The slideshow -->
  <div class="carousel-inner">
    
    <div class="carousel-item active">
      <img src="{{ url_for('static',
       filename='carousel_pics/car_1.jpeg')}}" alt="Los Angeles">
    </div>

    <div class="carousel-item">
      <img src="{{ url_for('static',
       filename='carousel_pics/car_2.jpeg')}}" alt="Los Angeles">
    </div>

    <div class="carousel-item">
      <img src="{{ url_for('static',
       filename='carousel_pics/car_3.jpeg')}}" alt="Los Angeles">
    </div>

  </div>
  
  <!-- Left and right controls -->
  <a class="carousel-control-prev" href="#demo" data-slide="prev">
    <span class="carousel-control-prev-icon"></span>
  </a>
  <a class="carousel-control-next" href="#demo" data-slide="next">
    <span class="carousel-control-next-icon"></span>
  </a>
</div>

	

{% endblock content %}

flaskBlog/templates/register.html
{% extends "layout.html" %}


{% block content %}

	<div class="form-section">
		<form method="POST" action="">
			{{ form.hidden_tag() }}
			<fieldset class="form-group">
				<legend class="border-bottom mb-4"> Join Today </legend>
				<div class="form-group">
					{{ form.username.label(class="form-control-label") }}

					{% if form.username.errors %}
						{{ form.username(class="form-control form-control-lg is-invalid") }}
						<div class="invalid-feedback">
							{% for error in form.username.errors %}
								<span>{{ error }}</span>
							{% endfor %}
						</div>	
					{% else %}
							{{ form.username(class="form-control form-control-lg") }}
				
					{% endif %}
				</div>
				<div class="form-group">
					{{ form.email.label(class="form-control-label") }}
					
					{% if form.email.errors %}
						{{ form.email(class="form-control form-control-lg is-invalid") }}
						<div class="invalid-feedback">
							{% for error in form.email.errors %}
								<span>{{ error }}</span>
							{% endfor %}
						</div>

					{% else %}
							{{ form.email(class="form-control form-control-lg") }}
				
					{% endif %}
				</div>
				<div class="form-group">
					{{ form.password.label(class="form-control-label") }}

					{% if form.password.errors %}
						{{ form.password(class="form-control form-control-lg is-invalid") }}
						<div class="invalid-feedback">
							{% for error in form.password.errors %}
								<span>{{ error }}</span>
							{%  endfor %}
						</div>

					{% else %}
							{{ form.password(class="form-control form-control-lg") }}
				
					{% endif %}
				</div>

				<div class="form-group">
					{{ form.confirm_password.label(class="form-control-label") }}
					
					{% if form.confirm_password.errors %}
						{{ form.confirm_password(class="form-control form-control-lg is-invalid") }}
						<div class="invalid-feedback">
							{% for error in form.confirm_password.errors %}
								<span>{{ error }}</span>
							{%  endfor %}
						</div>

					{% else %}
							{{ form.confirm_password(class="form-control form-control-lg") }}
				
					{% endif %}
				</div>

			</fieldset>
			<div class="form-group">
				{{ form.submit(class="btn btn-outline-info") }}
			</div>
		</form>
	</div>
	<div class="border-top pt-3">
		<small class="text-muted">
			Already Have an Account?
			<a class="ml-2" href=" {{ url_for('main.login') }} " > Sign In
			</a>
		</small>
	</div>

{% endblock content %}

flaskBlog/templates/reset_request.html
{% extends "layout.html" %}


{% block content %}

	<div class="form-section">
		<form method="POST" action="">
			{{ form.hidden_tag() }}
			<fieldset class="form-group">
				<legend class="border-bottom mb-4"> Reset Password </legend>
				
				<div class="form-group">
					{{ form.email.label(class="form-control-label") }}
					{% if form.email.errors %}
						{{ form.email(class="form-control form-control-lg is-invalid") }}
						<div class="invalid-feedback">
							{% for errors in form.email.errors%}
								<span>{{ error }}</span>
							{%  endfor %}
						</div>

					{% else %}
							{{ form.email(class="form-control form-control-lg") }}
				
					{% endif %}
				</div>
			</fieldset>
			<div class="form-group">
				{{ form.submit(class="btn btn-outline-info") }}
			</div>
		</form>
	</div>


{% endblock content %}

flaskBlog/templates/reset_token.html
{% extends "layout.html" %}


{% block content %}

	<div class="form-section">
		<form method="POST" action="">
			{{ form.hidden_tag() }}
			<fieldset class="form-group">
				<legend class="border-bottom mb-4"> Reset Password </legend>
				
				<div class="form-group">
					{{ form.password.label(class="form-control-label") }}
					{% if form.password.errors %}
						{{ form.password(class="form-control form-control-lg is-invalid") }}
						<div class="invalid-feedback">
							{% for errors in form.password.errors%}
								<span>{{ error }}</span>
							{%  endfor %}
						</div>

					{% else %}
							{{ form.password(class="form-control form-control-lg") }}
				
					{% endif %}
				</div>
				
				<div class="form-group">
					{{ form.confirm_password.label(class="form-control-label") }}
					{% if form.confirm_password.errors %}
						{{ form.confirm_password(class="form-control form-control-lg is-invalid") }}
						<div class="invalid-feedback">
							{% for errors in form.confirm_password.errors%}
								<span>{{ error }}</span>
							{%  endfor %}
						</div>

					{% else %}
							{{ form.confirm_password(class="form-control form-control-lg") }}
				
					{% endif %}
				</div>
			</fieldset>
			<div class="form-group">
				{{ form.submit(class="btn btn-outline-info") }}
			</div>
		</form>
	</div>


{% endblock content %}